# Generated by Django 5.2.6 on 2026-08-07 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(help_text='Item serial number', unique=True)),
                ('item', models.CharField(help_text='Item name and description', max_length=255)),
                ('old1', models.DecimalField(blank=True, decimal_places=2, help_text='First old price', max_digits=10, null=True)),
                ('old2', models.DecimalField(blank=True, decimal_places=2, help_text='Second old price', max_digits=10, null=True)),
                ('current1', models.DecimalField(decimal_places=2, help_text='First current price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current2', models.DecimalField(decimal_places=2, help_text='Second current price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('RICE', 'Rice'), ('DAL', 'Dal/Legumes'), ('OIL', 'Oil'), ('SPICE', 'Spices'), ('FLOUR', 'Flour'), ('GRAIN', 'Grain'), ('OTHER', 'Other')], default='OTHER', help_text='Item category', max_length=50)),
                ('unit', models.CharField(choices=[('KG', 'Per Kilogram'), ('LTR', 'Per Liter'), ('PC', 'Per Piece')], default='KG', help_text='Unit of measurement', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['no'],
                'indexes': [models.Index(fields=['no'], name='prices_mark_no_7258db_idx'), models.Index(fields=['category'], name='prices_mark_categor_5c9731_idx'), models.Index(fields=['is_active'], name='prices_mark_is_acti_ee45af_idx'), models.Index(fields=['last_updated'], name='prices_mark_last_up_d9e5ac_idx')],
            },
        ),
    ]
