# Generated by Django 5.2.6 on 2026-08-07 08:32

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notice title', max_length=500)),
                ('date', models.CharField(help_text='Date in Nepali format (e.g., २०८१ असार १५)', max_length=50)),
                ('full_content', ckeditor.fields.RichTextField(help_text='Full content of the notice with HTML formatting')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary of the notice', max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this notice is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured notice')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the notice was published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date', '-id'],
                'indexes': [models.Index(fields=['-published_date'], name='notices_not_publish_0b3a4a_idx'), models.Index(fields=['is_published'], name='notices_not_is_publ_3a63e9_idx'), models.Index(fields=['is_featured'], name='notices_not_is_feat_796ea0_idx'), models.Index(fields=['slug'], name='notices_not_slug_083f08_idx')],
            },
        ),
    ]
