# Generated by Django 5.2.6 on 2026-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='ठेगाना')),
                ('address_nepali', models.CharField(blank=True, max_length=500, verbose_name='ठेगाना (नेपाली)')),
                ('phone', models.CharField(max_length=20, verbose_name='फोन नम्बर')),
                ('phone_display', models.CharField(blank=True, max_length=50, verbose_name='फोन (प्रदर्शनको लागि)')),
                ('email', models.EmailField(max_length=254, verbose_name='इमेल')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps को embed URL', null=True, verbose_name='Google Maps Embed URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='अद्यावधिक मिति')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='सिर्जना मिति')),
            ],
        ),
    ]
