# Generated by Django 5.2.6 on 2026-08-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, unique=True, verbose_name='भेग')),
                ('zone_number', models.IntegerField(verbose_name='भेग नं.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Representative Zone',
                'verbose_name_plural': 'Representative Zones',
                'ordering': ['zone_number'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='नाम')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='ठेगाना')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='टेलिफोन नं.')),
                ('mobile', models.CharField(max_length=20, verbose_name='मोबाइल नं.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='representatives/', verbose_name='तस्वीर')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='representatives.representative')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
    ]
