# Generated by Django 5.2.6 on 2026-08-07 08:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Information title', max_length=500)),
                ('short_text', models.CharField(blank=True, help_text='Short description shown in card view', max_length=300)),
                ('full_content', models.TextField(help_text='Full content with HTML formatting')),
                ('image', models.ImageField(help_text='Upload an image for this information item', upload_to='info_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this item is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this is a featured item')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the item was published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information Item',
                'verbose_name_plural': 'Information Items',
                'ordering': ['-published_date', '-id'],
                'indexes': [models.Index(fields=['-published_date'], name='information_publish_d5771a_idx'), models.Index(fields=['is_published'], name='information_is_publ_37a2f6_idx'), models.Index(fields=['is_featured'], name='information_is_feat_6a643d_idx'), models.Index(fields=['slug'], name='information_slug_d8bbe5_idx')],
            },
        ),
    ]
