# Generated by Django 5.2.6 on 2026-08-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='program_images/')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
